backend:
  name: github
  repo: avolutiontech/auto
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/components/HeroSection.jsx"
        label: "Hero Section"
        name: "hero"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
